spring:
  cloud:
    gateway:
      routes:
        - id: bot-service
          uri: http://bot-service:8081
          predicates:
            - Path=/bot/**
          filters:
            - StripPrefix=1

        - id: parser-service
          uri: http://parser-service:8082
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1

        - id: notification-service
          uri: http://notification-service:8083
          predicates:
            - Path=/notification/**
          filters:
            - StripPrefix=1